export const replacements = [
  {
    search: />\s*AI Smart Trader\s*</g,
    replace: `>{t('auto.ai_smart_trader')}<`,
    key: 'auto.ai_smart_trader',
    en: 'AI Smart Trader',
    fr: 'AI Smart Trader',
  },
  {
    search: />\s*Loading price…\s*</g,
    replace: `>{t('auto.loading_price')}<`,
    key: 'auto.loading_price',
    en: 'Loading price…',
    fr: 'Loading price…',
  },
  {
    search: />\s*Error loading price for\s*</g,
    replace: `>{t('auto.error_loading_price_for')}<`,
    key: 'auto.error_loading_price_for',
    en: 'Error loading price for',
    fr: 'Error loading price for',
  },
  {
    search: />\s*No price data available\.\s*</g,
    replace: `>{t('auto.no_price_data_available')}<`,
    key: 'auto.no_price_data_available',
    en: 'No price data available.',
    fr: 'No price data available.',
  },
  {
    search: />\s*No data available\.\s*</g,
    replace: `>{t('auto.no_data_available')}<`,
    key: 'auto.no_data_available',
    en: 'No data available.',
    fr: 'No data available.',
  },
  {
    search:
      />\s*Select 2 to 3 strategies, define one shared period, then run 2-3 simulations in parallel\.\s*</g,
    replace: `>{t('auto.select_2_to_3_strategies_defin')}<`,
    key: 'auto.select_2_to_3_strategies_defin',
    en: 'Select 2 to 3 strategies, define one shared period, then run 2-3 simulations in parallel.',
    fr: 'Select 2 to 3 strategies, define one shared period, then run 2-3 simulations in parallel.',
  },
  {
    search: />\s*Period start\s*</g,
    replace: `>{t('auto.period_start')}<`,
    key: 'auto.period_start',
    en: 'Period start',
    fr: 'Period start',
  },
  {
    search: />\s*Period end\s*</g,
    replace: `>{t('auto.period_end')}<`,
    key: 'auto.period_end',
    en: 'Period end',
    fr: 'Period end',
  },
  {
    search: />\s*Use live AI for these parallel simulations\s*</g,
    replace: `>{t('auto.use_live_ai_for_these_parallel')}<`,
    key: 'auto.use_live_ai_for_these_parallel',
    en: 'Use live AI for these parallel simulations',
    fr: 'Use live AI for these parallel simulations',
  },
  {
    search: />\s*Best strategy\s*</g,
    replace: `>{t('auto.best_strategy')}<`,
    key: 'auto.best_strategy',
    en: 'Best strategy',
    fr: 'Best strategy',
  },
  {
    search: />\s*Comparison period\s*</g,
    replace: `>{t('auto.comparison_period')}<`,
    key: 'auto.comparison_period',
    en: 'Comparison period',
    fr: 'Comparison period',
  },
  {
    search: />\s*Rank\s*</g,
    replace: `>{t('auto.rank')}<`,
    key: 'auto.rank',
    en: 'Rank',
    fr: 'Rank',
  },
  {
    search: />\s*Strategy\s*</g,
    replace: `>{t('auto.strategy')}<`,
    key: 'auto.strategy',
    en: 'Strategy',
    fr: 'Strategy',
  },
  {
    search: />\s*Return\s*</g,
    replace: `>{t('auto.return')}<`,
    key: 'auto.return',
    en: 'Return',
    fr: 'Return',
  },
  {
    search: />\s*Net profit\s*</g,
    replace: `>{t('auto.net_profit')}<`,
    key: 'auto.net_profit',
    en: 'Net profit',
    fr: 'Net profit',
  },
  {
    search: />\s*Final value\s*</g,
    replace: `>{t('auto.final_value')}<`,
    key: 'auto.final_value',
    en: 'Final value',
    fr: 'Final value',
  },
  {
    search: />\s*Win rate\s*</g,
    replace: `>{t('auto.win_rate')}<`,
    key: 'auto.win_rate',
    en: 'Win rate',
    fr: 'Win rate',
  },
  {
    search: />\s*Operations\s*</g,
    replace: `>{t('auto.operations')}<`,
    key: 'auto.operations',
    en: 'Operations',
    fr: 'Operations',
  },
  {
    search: />\s*Δ vs best return\s*</g,
    replace: `>{t('auto.vs_best_return')}<`,
    key: 'auto.vs_best_return',
    en: 'Δ vs best return',
    fr: 'Δ vs best return',
  },
  {
    search: />\s*AI req\. total:\s*</g,
    replace: `>{t('auto.ai_req_total')}<`,
    key: 'auto.ai_req_total',
    en: 'AI req. total:',
    fr: 'AI req. total:',
  },
  {
    search: />\s*Live AI was not requested for this run\.\s*</g,
    replace: `>{t('auto.live_ai_was_not_requested_for')}<`,
    key: 'auto.live_ai_was_not_requested_for',
    en: 'Live AI was not requested for this run.',
    fr: 'Live AI was not requested for this run.',
  },
  {
    search: />\s*Executed operations\s*</g,
    replace: `>{t('auto.executed_operations')}<`,
    key: 'auto.executed_operations',
    en: 'Executed operations',
    fr: 'Executed operations',
  },
  {
    search: />\s*Total AI calls\s*</g,
    replace: `>{t('auto.total_ai_calls')}<`,
    key: 'auto.total_ai_calls',
    en: 'Total AI calls',
    fr: 'Total AI calls',
  },
  {
    search: />\s*Successful calls\s*</g,
    replace: `>{t('auto.successful_calls')}<`,
    key: 'auto.successful_calls',
    en: 'Successful calls',
    fr: 'Successful calls',
  },
  {
    search: />\s*Failed calls\s*</g,
    replace: `>{t('auto.failed_calls')}<`,
    key: 'auto.failed_calls',
    en: 'Failed calls',
    fr: 'Failed calls',
  },
  {
    search: />\s*Tokens consumed\s*</g,
    replace: `>{t('auto.tokens_consumed')}<`,
    key: 'auto.tokens_consumed',
    en: 'Tokens consumed',
    fr: 'Tokens consumed',
  },
  {
    search: />\s*Prompt tokens\s*</g,
    replace: `>{t('auto.prompt_tokens')}<`,
    key: 'auto.prompt_tokens',
    en: 'Prompt tokens',
    fr: 'Prompt tokens',
  },
  {
    search: />\s*Completion tokens\s*</g,
    replace: `>{t('auto.completion_tokens')}<`,
    key: 'auto.completion_tokens',
    en: 'Completion tokens',
    fr: 'Completion tokens',
  },
  {
    search: />\s*Current cost\s*</g,
    replace: `>{t('auto.current_cost')}<`,
    key: 'auto.current_cost',
    en: 'Current cost',
    fr: 'Current cost',
  },
  {
    search: />\s*Last 5 operations\s*</g,
    replace: `>{t('auto.last_5_operations')}<`,
    key: 'auto.last_5_operations',
    en: 'Last 5 operations',
    fr: 'Last 5 operations',
  },
  {
    search: />\s*No operations executed yet\.\s*</g,
    replace: `>{t('auto.no_operations_executed_yet')}<`,
    key: 'auto.no_operations_executed_yet',
    en: 'No operations executed yet.',
    fr: 'No operations executed yet.',
  },
  {
    search: />\s*Close\s*</g,
    replace: `>{t('auto.close')}<`,
    key: 'auto.close',
    en: 'Close',
    fr: 'Close',
  },
  {
    search: />\s*Simulation archives\s*</g,
    replace: `>{t('auto.simulation_archives')}<`,
    key: 'auto.simulation_archives',
    en: 'Simulation archives',
    fr: 'Simulation archives',
  },
  {
    search: />\s*Loading\.\.\.\s*</g,
    replace: `>{t('auto.loading')}<`,
    key: 'auto.loading',
    en: 'Loading...',
    fr: 'Loading...',
  },
  {
    search: />\s*No archived simulation yet\.\s*</g,
    replace: `>{t('auto.no_archived_simulation_yet')}<`,
    key: 'auto.no_archived_simulation_yet',
    en: 'No archived simulation yet.',
    fr: 'No archived simulation yet.',
  },
  {
    search: />\s*Status\s*</g,
    replace: `>{t('auto.status')}<`,
    key: 'auto.status',
    en: 'Status',
    fr: 'Status',
  },
  { search: />\s*All\s*</g, replace: `>{t('auto.all')}<`, key: 'auto.all', en: 'All', fr: 'All' },
  {
    search: />\s*Completed\s*</g,
    replace: `>{t('auto.completed')}<`,
    key: 'auto.completed',
    en: 'Completed',
    fr: 'Completed',
  },
  {
    search: />\s*Failed\s*</g,
    replace: `>{t('auto.failed')}<`,
    key: 'auto.failed',
    en: 'Failed',
    fr: 'Failed',
  },
  {
    search: />\s*Rows\/page\s*</g,
    replace: `>{t('auto.rows_page')}<`,
    key: 'auto.rows_page',
    en: 'Rows/page',
    fr: 'Rows/page',
  },
  {
    search: />\s*Execution date\s*</g,
    replace: `>{t('auto.execution_date')}<`,
    key: 'auto.execution_date',
    en: 'Execution date',
    fr: 'Execution date',
  },
  {
    search: />\s*Period\s*</g,
    replace: `>{t('auto.period')}<`,
    key: 'auto.period',
    en: 'Period',
    fr: 'Period',
  },
  {
    search: />\s*Invested\s*</g,
    replace: `>{t('auto.invested')}<`,
    key: 'auto.invested',
    en: 'Invested',
    fr: 'Invested',
  },
  { search: />\s*PnL\s*</g, replace: `>{t('auto.pnl')}<`, key: 'auto.pnl', en: 'PnL', fr: 'PnL' },
  {
    search: />\s*Batch\s*</g,
    replace: `>{t('auto.batch')}<`,
    key: 'auto.batch',
    en: 'Batch',
    fr: 'Batch',
  },
  {
    search: />\s*Action\s*</g,
    replace: `>{t('auto.action')}<`,
    key: 'auto.action',
    en: 'Action',
    fr: 'Action',
  },
  {
    search: />\s*View details\s*</g,
    replace: `>{t('auto.view_details')}<`,
    key: 'auto.view_details',
    en: 'View details',
    fr: 'View details',
  },
  {
    search: />\s*Delete\s*</g,
    replace: `>{t('auto.delete')}<`,
    key: 'auto.delete',
    en: 'Delete',
    fr: 'Delete',
  },
  {
    search: />\s*No simulations for these filters\.\s*</g,
    replace: `>{t('auto.no_simulations_for_these_filte')}<`,
    key: 'auto.no_simulations_for_these_filte',
    en: 'No simulations for these filters.',
    fr: 'No simulations for these filters.',
  },
  {
    search: />\s*Previous\s*</g,
    replace: `>{t('auto.previous')}<`,
    key: 'auto.previous',
    en: 'Previous',
    fr: 'Previous',
  },
  {
    search: />\s*Next\s*</g,
    replace: `>{t('auto.next')}<`,
    key: 'auto.next',
    en: 'Next',
    fr: 'Next',
  },
  {
    search: />\s*null,\s*</g,
    replace: `>{t('auto.null')}<`,
    key: 'auto.null',
    en: 'null,',
    fr: 'null,',
  },
  {
    search: />\s*\): Promise\s*</g,
    replace: `>{t('auto.promise')}<`,
    key: 'auto.promise',
    en: '): Promise',
    fr: '): Promise',
  },
  {
    search: />\s*OpenAI\s*</g,
    replace: `>{t('auto.openai')}<`,
    key: 'auto.openai',
    en: 'OpenAI',
    fr: 'OpenAI',
  },
  {
    search: />\s*Anthropic\s*</g,
    replace: `>{t('auto.anthropic')}<`,
    key: 'auto.anthropic',
    en: 'Anthropic',
    fr: 'Anthropic',
  },
  {
    search: />\s*Google Gemini\s*</g,
    replace: `>{t('auto.google_gemini')}<`,
    key: 'auto.google_gemini',
    en: 'Google Gemini',
    fr: 'Google Gemini',
  },
  {
    search: />\s*You can create multiple prompts per type to compare algorithm behaviors\.\s*</g,
    replace: `>{t('auto.you_can_create_multiple_prompt')}<`,
    key: 'auto.you_can_create_multiple_prompt',
    en: 'You can create multiple prompts per type to compare algorithm behaviors.',
    fr: 'You can create multiple prompts per type to compare algorithm behaviors.',
  },
  {
    search: />\s*Prompt type\s*</g,
    replace: `>{t('auto.prompt_type')}<`,
    key: 'auto.prompt_type',
    en: 'Prompt type',
    fr: 'Prompt type',
  },
  {
    search: />\s*AI Advisor - System\s*</g,
    replace: `>{t('auto.ai_advisor_system')}<`,
    key: 'auto.ai_advisor_system',
    en: 'AI Advisor - System',
    fr: 'AI Advisor - System',
  },
  {
    search: />\s*AI Advisor - Context\s*</g,
    replace: `>{t('auto.ai_advisor_context')}<`,
    key: 'auto.ai_advisor_context',
    en: 'AI Advisor - Context',
    fr: 'AI Advisor - Context',
  },
  {
    search: />\s*Simulation - Explanation\s*</g,
    replace: `>{t('auto.simulation_explanation')}<`,
    key: 'auto.simulation_explanation',
    en: 'Simulation - Explanation',
    fr: 'Simulation - Explanation',
  },
  {
    search: />\s*Name\s*</g,
    replace: `>{t('auto.name')}<`,
    key: 'auto.name',
    en: 'Name',
    fr: 'Name',
  },
  {
    search: />\s*Description\s*</g,
    replace: `>{t('auto.description')}<`,
    key: 'auto.description',
    en: 'Description',
    fr: 'Description',
  },
  {
    search: />\s*Prompt content\s*</g,
    replace: `>{t('auto.prompt_content')}<`,
    key: 'auto.prompt_content',
    en: 'Prompt content',
    fr: 'Prompt content',
  },
  {
    search: />\s*Reset form\s*</g,
    replace: `>{t('auto.reset_form')}<`,
    key: 'auto.reset_form',
    en: 'Reset form',
    fr: 'Reset form',
  },
  {
    search: />\s*Restore all defaults\s*</g,
    replace: `>{t('auto.restore_all_defaults')}<`,
    key: 'auto.restore_all_defaults',
    en: 'Restore all defaults',
    fr: 'Restore all defaults',
  },
  {
    search: />\s*Quick help\s*</g,
    replace: `>{t('auto.quick_help')}<`,
    key: 'auto.quick_help',
    en: 'Quick help',
    fr: 'Quick help',
  },
  {
    search: />\s*Multiple variants\s*</g,
    replace: `>{t('auto.multiple_variants')}<`,
    key: 'auto.multiple_variants',
    en: 'Multiple variants',
    fr: 'Multiple variants',
  },
  {
    search: />\s*Create multiple prompts of the same type for A\/B testing\.\s*</g,
    replace: `>{t('auto.create_multiple_prompts_of_the')}<`,
    key: 'auto.create_multiple_prompts_of_the',
    en: 'Create multiple prompts of the same type for A/B testing.',
    fr: 'Create multiple prompts of the same type for A/B testing.',
  },
  {
    search: />\s*Default version\s*</g,
    replace: `>{t('auto.default_version')}<`,
    key: 'auto.default_version',
    en: 'Default version',
    fr: 'Default version',
  },
  {
    search: />\s*Prompts shipped with the project remain available and can be restored\.\s*</g,
    replace: `>{t('auto.prompts_shipped_with_the_proje')}<`,
    key: 'auto.prompts_shipped_with_the_proje',
    en: 'Prompts shipped with the project remain available and can be restored.',
    fr: 'Prompts shipped with the project remain available and can be restored.',
  },
  {
    search: />\s*Strategy setup\s*</g,
    replace: `>{t('auto.strategy_setup')}<`,
    key: 'auto.strategy_setup',
    en: 'Strategy setup',
    fr: 'Strategy setup',
  },
  {
    search: />\s*Each strategy can choose its AI prompts in the Strategies page\.\s*</g,
    replace: `>{t('auto.each_strategy_can_choose_its_a')}<`,
    key: 'auto.each_strategy_can_choose_its_a',
    en: 'Each strategy can choose its AI prompts in the Strategies page.',
    fr: 'Each strategy can choose its AI prompts in the Strategies page.',
  },
  { search: />\s*ID\s*</g, replace: `>{t('auto.id')}<`, key: 'auto.id', en: 'ID', fr: 'ID' },
  {
    search: />\s*Default\s*</g,
    replace: `>{t('auto.default')}<`,
    key: 'auto.default',
    en: 'Default',
    fr: 'Default',
  },
  {
    search: />\s*Actions\s*</g,
    replace: `>{t('auto.actions')}<`,
    key: 'auto.actions',
    en: 'Actions',
    fr: 'Actions',
  },
  {
    search: />\s*Edit\s*</g,
    replace: `>{t('auto.edit')}<`,
    key: 'auto.edit',
    en: 'Edit',
    fr: 'Edit',
  },
  {
    search: />\s*Reset to default\s*</g,
    replace: `>{t('auto.reset_to_default')}<`,
    key: 'auto.reset_to_default',
    en: 'Reset to default',
    fr: 'Reset to default',
  },
  {
    search: />\s*Tokens used\s*</g,
    replace: `>{t('auto.tokens_used')}<`,
    key: 'auto.tokens_used',
    en: 'Tokens used',
    fr: 'Tokens used',
  },
  {
    search: />\s*Estimated cost\s*</g,
    replace: `>{t('auto.estimated_cost')}<`,
    key: 'auto.estimated_cost',
    en: 'Estimated cost',
    fr: 'Estimated cost',
  },
  {
    search: />\s*Success\s*</g,
    replace: `>{t('auto.success')}<`,
    key: 'auto.success',
    en: 'Success',
    fr: 'Success',
  },
  {
    search: />\s*Error\s*</g,
    replace: `>{t('auto.error')}<`,
    key: 'auto.error',
    en: 'Error',
    fr: 'Error',
  },
  {
    search: />\s*Model\s*</g,
    replace: `>{t('auto.model')}<`,
    key: 'auto.model',
    en: 'Model',
    fr: 'Model',
  },
  {
    search: />\s*No calls for these filters\.\s*</g,
    replace: `>{t('auto.no_calls_for_these_filters')}<`,
    key: 'auto.no_calls_for_these_filters',
    en: 'No calls for these filters.',
    fr: 'No calls for these filters.',
  },
  {
    search: />\s*useState\s*</g,
    replace: `>{t('auto.usestate')}<`,
    key: 'auto.usestate',
    en: 'useState',
    fr: 'useState',
  },
  {
    search: />\s*if \(returns\.length\s*</g,
    replace: `>{t('auto.if_returns_length')}<`,
    key: 'auto.if_returns_length',
    en: 'if (returns.length',
    fr: 'if (returns.length',
  },
  {
    search: />\s*Analyzed strategy\s*</g,
    replace: `>{t('auto.analyzed_strategy')}<`,
    key: 'auto.analyzed_strategy',
    en: 'Analyzed strategy',
    fr: 'Analyzed strategy',
  },
  {
    search: />\s*Market regime\s*</g,
    replace: `>{t('auto.market_regime')}<`,
    key: 'auto.market_regime',
    en: 'Market regime',
    fr: 'Market regime',
  },
  {
    search: />\s*Risk\s*</g,
    replace: `>{t('auto.risk')}<`,
    key: 'auto.risk',
    en: 'Risk',
    fr: 'Risk',
  },
  {
    search: />\s*Confidence\s*</g,
    replace: `>{t('auto.confidence')}<`,
    key: 'auto.confidence',
    en: 'Confidence',
    fr: 'Confidence',
  },
  {
    search: />\s*30d volatility\s*</g,
    replace: `>{t('auto.30d_volatility')}<`,
    key: 'auto.30d_volatility',
    en: '30d volatility',
    fr: '30d volatility',
  },
  {
    search: />\s*Recommendations\s*</g,
    replace: `>{t('auto.recommendations')}<`,
    key: 'auto.recommendations',
    en: 'Recommendations',
    fr: 'Recommendations',
  },
  {
    search: />\s*Alerts\s*</g,
    replace: `>{t('auto.alerts')}<`,
    key: 'auto.alerts',
    en: 'Alerts',
    fr: 'Alerts',
  },
  {
    search: />\s*Session active\s*</g,
    replace: `>{t('auto.session_active')}<`,
    key: 'auto.session_active',
    en: 'Session active',
    fr: 'Session active',
  },
  {
    search: />\s*Open dashboard\s*</g,
    replace: `>{t('auto.open_dashboard')}<`,
    key: 'auto.open_dashboard',
    en: 'Open dashboard',
    fr: 'Open dashboard',
  },
  {
    search: />\s*Sign-in required\s*</g,
    replace: `>{t('auto.sign_in_required')}<`,
    key: 'auto.sign_in_required',
    en: 'Sign-in required',
    fr: 'Sign-in required',
  },
  {
    search: />\s*Access dashboard\s*</g,
    replace: `>{t('auto.access_dashboard')}<`,
    key: 'auto.access_dashboard',
    en: 'Access dashboard',
    fr: 'Access dashboard',
  },
  {
    search: />\s*Sign in with Google\s*</g,
    replace: `>{t('auto.sign_in_with_google')}<`,
    key: 'auto.sign_in_with_google',
    en: 'Sign in with Google',
    fr: 'Sign in with Google',
  },
  {
    search: />\s*Market Overview\s*</g,
    replace: `>{t('auto.market_overview')}<`,
    key: 'auto.market_overview',
    en: 'Market Overview',
    fr: 'Market Overview',
  },
  {
    search: />\s*Execution\s*</g,
    replace: `>{t('auto.execution')}<`,
    key: 'auto.execution',
    en: 'Execution',
    fr: 'Execution',
  },
  {
    search: />\s*Decision\s*</g,
    replace: `>{t('auto.decision')}<`,
    key: 'auto.decision',
    en: 'Decision',
    fr: 'Decision',
  },
  {
    search: />\s*Expected gain\s*</g,
    replace: `>{t('auto.expected_gain')}<`,
    key: 'auto.expected_gain',
    en: 'Expected gain',
    fr: 'Expected gain',
  },
  {
    search: />\s*AI recommendation\s*</g,
    replace: `>{t('auto.ai_recommendation')}<`,
    key: 'auto.ai_recommendation',
    en: 'AI recommendation',
    fr: 'AI recommendation',
  },
  {
    search: />\s*Goal contribution\s*</g,
    replace: `>{t('auto.goal_contribution')}<`,
    key: 'auto.goal_contribution',
    en: 'Goal contribution',
    fr: 'Goal contribution',
  },
  {
    search: />\s*First name\s*</g,
    replace: `>{t('auto.first_name')}<`,
    key: 'auto.first_name',
    en: 'First name',
    fr: 'First name',
  },
  {
    search: />\s*Last name\s*</g,
    replace: `>{t('auto.last_name')}<`,
    key: 'auto.last_name',
    en: 'Last name',
    fr: 'Last name',
  },
  {
    search: />\s*Date of birth\s*</g,
    replace: `>{t('auto.date_of_birth')}<`,
    key: 'auto.date_of_birth',
    en: 'Date of birth',
    fr: 'Date of birth',
  },
  {
    search: />\s*Country\s*</g,
    replace: `>{t('auto.country')}<`,
    key: 'auto.country',
    en: 'Country',
    fr: 'Country',
  },
  {
    search: />\s*City\s*</g,
    replace: `>{t('auto.city')}<`,
    key: 'auto.city',
    en: 'City',
    fr: 'City',
  },
  {
    search: />\s*Time zone\s*</g,
    replace: `>{t('auto.time_zone')}<`,
    key: 'auto.time_zone',
    en: 'Time zone',
    fr: 'Time zone',
  },
  {
    search: />\s*Occupation\s*</g,
    replace: `>{t('auto.occupation')}<`,
    key: 'auto.occupation',
    en: 'Occupation',
    fr: 'Occupation',
  },
  {
    search: />\s*Investment experience level\s*</g,
    replace: `>{t('auto.investment_experience_level')}<`,
    key: 'auto.investment_experience_level',
    en: 'Investment experience level',
    fr: 'Investment experience level',
  },
  {
    search: />\s*Beginner\s*</g,
    replace: `>{t('auto.beginner')}<`,
    key: 'auto.beginner',
    en: 'Beginner',
    fr: 'Beginner',
  },
  {
    search: />\s*Intermediate\s*</g,
    replace: `>{t('auto.intermediate')}<`,
    key: 'auto.intermediate',
    en: 'Intermediate',
    fr: 'Intermediate',
  },
  {
    search: />\s*Advanced\s*</g,
    replace: `>{t('auto.advanced')}<`,
    key: 'auto.advanced',
    en: 'Advanced',
    fr: 'Advanced',
  },
  {
    search: />\s*Bio \/ goals\s*</g,
    replace: `>{t('auto.bio_goals')}<`,
    key: 'auto.bio_goals',
    en: 'Bio / goals',
    fr: 'Bio / goals',
  },
  {
    search: />\s*Prompt library\s*</g,
    replace: `>{t('auto.prompt_library')}<`,
    key: 'auto.prompt_library',
    en: 'Prompt library',
    fr: 'Prompt library',
  },
  {
    search: />\s*Back to parent simulation\s*</g,
    replace: `>{t('auto.back_to_parent_simulation')}<`,
    key: 'auto.back_to_parent_simulation',
    en: 'Back to parent simulation',
    fr: 'Back to parent simulation',
  },
  {
    search: />\s*Previous operation\s*</g,
    replace: `>{t('auto.previous_operation')}<`,
    key: 'auto.previous_operation',
    en: 'Previous operation',
    fr: 'Previous operation',
  },
  {
    search: />\s*Next operation\s*</g,
    replace: `>{t('auto.next_operation')}<`,
    key: 'auto.next_operation',
    en: 'Next operation',
    fr: 'Next operation',
  },
  {
    search: />\s*Spot price at time T\s*</g,
    replace: `>{t('auto.spot_price_at_time_t')}<`,
    key: 'auto.spot_price_at_time_t',
    en: 'Spot price at time T',
    fr: 'Spot price at time T',
  },
  {
    search: />\s*Portfolio value\s*</g,
    replace: `>{t('auto.portfolio_value')}<`,
    key: 'auto.portfolio_value',
    en: 'Portfolio value',
    fr: 'Portfolio value',
  },
  {
    search: />\s*Available cash\s*</g,
    replace: `>{t('auto.available_cash')}<`,
    key: 'auto.available_cash',
    en: 'Available cash',
    fr: 'Available cash',
  },
  {
    search: />\s*Cumulative invested\s*</g,
    replace: `>{t('auto.cumulative_invested')}<`,
    key: 'auto.cumulative_invested',
    en: 'Cumulative invested',
    fr: 'Cumulative invested',
  },
  {
    search: />\s*Position before order\s*</g,
    replace: `>{t('auto.position_before_order')}<`,
    key: 'auto.position_before_order',
    en: 'Position before order',
    fr: 'Position before order',
  },
  {
    search: />\s*Asset weight before order\s*</g,
    replace: `>{t('auto.asset_weight_before_order')}<`,
    key: 'auto.asset_weight_before_order',
    en: 'Asset weight before order',
    fr: 'Asset weight before order',
  },
  {
    search: />\s*Decision rationale\s*</g,
    replace: `>{t('auto.decision_rationale')}<`,
    key: 'auto.decision_rationale',
    en: 'Decision rationale',
    fr: 'Decision rationale',
  },
  {
    search: />\s*Financial impact\s*</g,
    replace: `>{t('auto.financial_impact')}<`,
    key: 'auto.financial_impact',
    en: 'Financial impact',
    fr: 'Financial impact',
  },
  {
    search: />\s*← Back to simulations\s*</g,
    replace: `>{t('auto.back_to_simulations')}<`,
    key: 'auto.back_to_simulations',
    en: '← Back to simulations',
    fr: '← Back to simulations',
  },
  {
    search: />\s*Previous simulation\s*</g,
    replace: `>{t('auto.previous_simulation')}<`,
    key: 'auto.previous_simulation',
    en: 'Previous simulation',
    fr: 'Previous simulation',
  },
  {
    search: />\s*Next simulation\s*</g,
    replace: `>{t('auto.next_simulation')}<`,
    key: 'auto.next_simulation',
    en: 'Next simulation',
    fr: 'Next simulation',
  },
  {
    search: />\s*Total invested\s*</g,
    replace: `>{t('auto.total_invested')}<`,
    key: 'auto.total_invested',
    en: 'Total invested',
    fr: 'Total invested',
  },
  {
    search: />\s*Net gain\/loss\s*</g,
    replace: `>{t('auto.net_gain_loss')}<`,
    key: 'auto.net_gain_loss',
    en: 'Net gain/loss',
    fr: 'Net gain/loss',
  },
  {
    search: />\s*Fees\s*</g,
    replace: `>{t('auto.fees')}<`,
    key: 'auto.fees',
    en: 'Fees',
    fr: 'Fees',
  },
  {
    search: />\s*AI calls\s*</g,
    replace: `>{t('auto.ai_calls')}<`,
    key: 'auto.ai_calls',
    en: 'AI calls',
    fr: 'AI calls',
  },
  {
    search: />\s*AI calls successful\s*</g,
    replace: `>{t('auto.ai_calls_successful')}<`,
    key: 'auto.ai_calls_successful',
    en: 'AI calls successful',
    fr: 'AI calls successful',
  },
  {
    search: />\s*AI calls failed\s*</g,
    replace: `>{t('auto.ai_calls_failed')}<`,
    key: 'auto.ai_calls_failed',
    en: 'AI calls failed',
    fr: 'AI calls failed',
  },
  {
    search: />\s*AI tokens\s*</g,
    replace: `>{t('auto.ai_tokens')}<`,
    key: 'auto.ai_tokens',
    en: 'AI tokens',
    fr: 'AI tokens',
  },
  {
    search: />\s*AI cost\s*</g,
    replace: `>{t('auto.ai_cost')}<`,
    key: 'auto.ai_cost',
    en: 'AI cost',
    fr: 'AI cost',
  },
  {
    search: />\s*Asset price curves by crypto\s*</g,
    replace: `>{t('auto.asset_price_curves_by_crypto')}<`,
    key: 'auto.asset_price_curves_by_crypto',
    en: 'Asset price curves by crypto',
    fr: 'Asset price curves by crypto',
  },
  {
    search: />\s*chart per crypto\.\s*</g,
    replace: `>{t('auto.chart_per_crypto')}<`,
    key: 'auto.chart_per_crypto',
    en: 'chart per crypto.',
    fr: 'chart per crypto.',
  },
  {
    search: />\s*No operation data available to build asset price curves\.\s*</g,
    replace: `>{t('auto.no_operation_data_available_to')}<`,
    key: 'auto.no_operation_data_available_to',
    en: 'No operation data available to build asset price curves.',
    fr: 'No operation data available to build asset price curves.',
  },
  {
    search: />\s*Buy filled\s*</g,
    replace: `>{t('auto.buy_filled')}<`,
    key: 'auto.buy_filled',
    en: 'Buy filled',
    fr: 'Buy filled',
  },
  {
    search: />\s*Sell filled\s*</g,
    replace: `>{t('auto.sell_filled')}<`,
    key: 'auto.sell_filled',
    en: 'Sell filled',
    fr: 'Sell filled',
  },
  {
    search: />\s*Buy rejected\s*</g,
    replace: `>{t('auto.buy_rejected')}<`,
    key: 'auto.buy_rejected',
    en: 'Buy rejected',
    fr: 'Buy rejected',
  },
  {
    search: />\s*Sell rejected\s*</g,
    replace: `>{t('auto.sell_rejected')}<`,
    key: 'auto.sell_rejected',
    en: 'Sell rejected',
    fr: 'Sell rejected',
  },
  {
    search: />\s*Portfolio vs invested evolution\s*</g,
    replace: `>{t('auto.portfolio_vs_invested_evolutio')}<`,
    key: 'auto.portfolio_vs_invested_evolutio',
    en: 'Portfolio vs invested evolution',
    fr: 'Portfolio vs invested evolution',
  },
  {
    search:
      />\s*Compare portfolio value to invested capital: above means overall gain, below means\s*</g,
    replace: `>{t('auto.compare_portfolio_value_to_inv')}<`,
    key: 'auto.compare_portfolio_value_to_inv',
    en: 'Compare portfolio value to invested capital: above means overall gain, below means',
    fr: 'Compare portfolio value to invested capital: above means overall gain, below means',
  },
  {
    search: />\s*overall loss\.\s*</g,
    replace: `>{t('auto.overall_loss')}<`,
    key: 'auto.overall_loss',
    en: 'overall loss.',
    fr: 'overall loss.',
  },
  {
    search: />\s*Gain\/loss evolution\s*</g,
    replace: `>{t('auto.gain_loss_evolution')}<`,
    key: 'auto.gain_loss_evolution',
    en: 'Gain/loss evolution',
    fr: 'Gain/loss evolution',
  },
  {
    search:
      />\s*This chart shows net gain\/loss over time: positive means profit, negative means\s*</g,
    replace: `>{t('auto.this_chart_shows_net_gain_loss')}<`,
    key: 'auto.this_chart_shows_net_gain_loss',
    en: 'This chart shows net gain/loss over time: positive means profit, negative means',
    fr: 'This chart shows net gain/loss over time: positive means profit, negative means',
  },
  {
    search: />\s*loss\.\s*</g,
    replace: `>{t('auto.loss')}<`,
    key: 'auto.loss',
    en: 'loss.',
    fr: 'loss.',
  },
  {
    search: />\s*AI usage evolution\s*</g,
    replace: `>{t('auto.ai_usage_evolution')}<`,
    key: 'auto.ai_usage_evolution',
    en: 'AI usage evolution',
    fr: 'AI usage evolution',
  },
  {
    search:
      />\s*Cumulative AI remote calls during the simulation, with successful and failed calls\s*</g,
    replace: `>{t('auto.cumulative_ai_remote_calls_dur')}<`,
    key: 'auto.cumulative_ai_remote_calls_dur',
    en: 'Cumulative AI remote calls during the simulation, with successful and failed calls',
    fr: 'Cumulative AI remote calls during the simulation, with successful and failed calls',
  },
  {
    search: />\s*over time\.\s*</g,
    replace: `>{t('auto.over_time')}<`,
    key: 'auto.over_time',
    en: 'over time.',
    fr: 'over time.',
  },
  {
    search: />\s*AI recommendation evolution\s*</g,
    replace: `>{t('auto.ai_recommendation_evolution')}<`,
    key: 'auto.ai_recommendation_evolution',
    en: 'AI recommendation evolution',
    fr: 'AI recommendation evolution',
  },
  {
    search: />\s*Cumulative recommendation flow by action type and source\.\s*</g,
    replace: `>{t('auto.cumulative_recommendation_flow')}<`,
    key: 'auto.cumulative_recommendation_flow',
    en: 'Cumulative recommendation flow by action type and source.',
    fr: 'Cumulative recommendation flow by action type and source.',
  },
  {
    search: />\s*Simulation operations\s*</g,
    replace: `>{t('auto.simulation_operations')}<`,
    key: 'auto.simulation_operations',
    en: 'Simulation operations',
    fr: 'Simulation operations',
  },
  {
    search: />\s*Side\s*</g,
    replace: `>{t('auto.side')}<`,
    key: 'auto.side',
    en: 'Side',
    fr: 'Side',
  },
  { search: />\s*Buy\s*</g, replace: `>{t('auto.buy')}<`, key: 'auto.buy', en: 'Buy', fr: 'Buy' },
  {
    search: />\s*Sell\s*</g,
    replace: `>{t('auto.sell')}<`,
    key: 'auto.sell',
    en: 'Sell',
    fr: 'Sell',
  },
  {
    search: />\s*Outcome\s*</g,
    replace: `>{t('auto.outcome')}<`,
    key: 'auto.outcome',
    en: 'Outcome',
    fr: 'Outcome',
  },
  {
    search: />\s*Successful\s*</g,
    replace: `>{t('auto.successful')}<`,
    key: 'auto.successful',
    en: 'Successful',
    fr: 'Successful',
  },
  {
    search: />\s*Asset\s*</g,
    replace: `>{t('auto.asset')}<`,
    key: 'auto.asset',
    en: 'Asset',
    fr: 'Asset',
  },
  {
    search: />\s*Timestamp\s*</g,
    replace: `>{t('auto.timestamp')}<`,
    key: 'auto.timestamp',
    en: 'Timestamp',
    fr: 'Timestamp',
  },
  {
    search: />\s*Amount\s*</g,
    replace: `>{t('auto.amount')}<`,
    key: 'auto.amount',
    en: 'Amount',
    fr: 'Amount',
  },
  {
    search: />\s*Price\s*</g,
    replace: `>{t('auto.price')}<`,
    key: 'auto.price',
    en: 'Price',
    fr: 'Price',
  },
  {
    search: />\s*Rationale\s*</g,
    replace: `>{t('auto.rationale')}<`,
    key: 'auto.rationale',
    en: 'Rationale',
    fr: 'Rationale',
  },
  {
    search: />\s*Detail\s*</g,
    replace: `>{t('auto.detail')}<`,
    key: 'auto.detail',
    en: 'Detail',
    fr: 'Detail',
  },
  {
    search: />\s*Open\s*</g,
    replace: `>{t('auto.open')}<`,
    key: 'auto.open',
    en: 'Open',
    fr: 'Open',
  },
  {
    search: />\s*No operations for these filters\.\s*</g,
    replace: `>{t('auto.no_operations_for_these_filter')}<`,
    key: 'auto.no_operations_for_these_filter',
    en: 'No operations for these filters.',
    fr: 'No operations for these filters.',
  },
  {
    search: />\s*'period',\s*</g,
    replace: `>{t('auto.period')}<`,
    key: 'auto.period',
    en: "'period',",
    fr: "'period',",
  },
  {
    search: />\s*if \(periods\.length\s*</g,
    replace: `>{t('auto.if_periods_length')}<`,
    key: 'auto.if_periods_length',
    en: 'if (periods.length',
    fr: 'if (periods.length',
  },
  {
    search: />\s*New simulation\s*</g,
    replace: `>{t('auto.new_simulation')}<`,
    key: 'auto.new_simulation',
    en: 'New simulation',
    fr: 'New simulation',
  },
  {
    search: />\s*Start\s*</g,
    replace: `>{t('auto.start')}<`,
    key: 'auto.start',
    en: 'Start',
    fr: 'Start',
  },
  { search: />\s*End\s*</g, replace: `>{t('auto.end')}<`, key: 'auto.end', en: 'End', fr: 'End' },
  {
    search: />\s*Override strategy for this test\s*</g,
    replace: `>{t('auto.override_strategy_for_this_tes')}<`,
    key: 'auto.override_strategy_for_this_tes',
    en: 'Override strategy for this test',
    fr: 'Override strategy for this test',
  },
  {
    search: />\s*Risk profile\s*</g,
    replace: `>{t('auto.risk_profile')}<`,
    key: 'auto.risk_profile',
    en: 'Risk profile',
    fr: 'Risk profile',
  },
  {
    search: />\s*defensive\s*</g,
    replace: `>{t('auto.defensive')}<`,
    key: 'auto.defensive',
    en: 'defensive',
    fr: 'defensive',
  },
  {
    search: />\s*balanced\s*</g,
    replace: `>{t('auto.balanced')}<`,
    key: 'auto.balanced',
    en: 'balanced',
    fr: 'balanced',
  },
  {
    search: />\s*aggressive\s*</g,
    replace: `>{t('auto.aggressive')}<`,
    key: 'auto.aggressive',
    en: 'aggressive',
    fr: 'aggressive',
  },
  {
    search: />\s*Cycles \/ day\s*</g,
    replace: `>{t('auto.cycles_day')}<`,
    key: 'auto.cycles_day',
    en: 'Cycles / day',
    fr: 'Cycles / day',
  },
  {
    search: />\s*Reset\s*</g,
    replace: `>{t('auto.reset')}<`,
    key: 'auto.reset',
    en: 'Reset',
    fr: 'Reset',
  },
  {
    search: />\s*Simulation rules\s*</g,
    replace: `>{t('auto.simulation_rules')}<`,
    key: 'auto.simulation_rules',
    en: 'Simulation rules',
    fr: 'Simulation rules',
  },
  {
    search: />\s*Initial capital\s*</g,
    replace: `>{t('auto.initial_capital')}<`,
    key: 'auto.initial_capital',
    en: 'Initial capital',
    fr: 'Initial capital',
  },
  {
    search: />\s*300 EUR injected at the start date\.\s*</g,
    replace: `>{t('auto.300_eur_injected_at_the_start')}<`,
    key: 'auto.300_eur_injected_at_the_start',
    en: '300 EUR injected at the start date.',
    fr: '300 EUR injected at the start date.',
  },
  {
    search: />\s*Monthly contributions\s*</g,
    replace: `>{t('auto.monthly_contributions')}<`,
    key: 'auto.monthly_contributions',
    en: 'Monthly contributions',
    fr: 'Monthly contributions',
  },
  {
    search: />\s*The strategy monthly budget is added at the start of each following month\.\s*</g,
    replace: `>{t('auto.the_strategy_monthly_budget_is')}<`,
    key: 'auto.the_strategy_monthly_budget_is',
    en: 'The strategy monthly budget is added at the start of each following month.',
    fr: 'The strategy monthly budget is added at the start of each following month.',
  },
  {
    search: />\s*No look-ahead bias\s*</g,
    replace: `>{t('auto.no_look_ahead_bias')}<`,
    key: 'auto.no_look_ahead_bias',
    en: 'No look-ahead bias',
    fr: 'No look-ahead bias',
  },
  {
    search: />\s*On each date, decisions use only historical data available up to that date\.\s*</g,
    replace: `>{t('auto.on_each_date_decisions_use_onl')}<`,
    key: 'auto.on_each_date_decisions_use_onl',
    en: 'On each date, decisions use only historical data available up to that date.',
    fr: 'On each date, decisions use only historical data available up to that date.',
  },
  {
    search: />\s*Monte Carlo iterations\s*</g,
    replace: `>{t('auto.monte_carlo_iterations')}<`,
    key: 'auto.monte_carlo_iterations',
    en: 'Monte Carlo iterations',
    fr: 'Monte Carlo iterations',
  },
  {
    search: />\s*Presets\s*</g,
    replace: `>{t('auto.presets')}<`,
    key: 'auto.presets',
    en: 'Presets',
    fr: 'Presets',
  },
  {
    search: />\s*Average return\s*</g,
    replace: `>{t('auto.average_return')}<`,
    key: 'auto.average_return',
    en: 'Average return',
    fr: 'Average return',
  },
  {
    search: />\s*Positive period rate\s*</g,
    replace: `>{t('auto.positive_period_rate')}<`,
    key: 'auto.positive_period_rate',
    en: 'Positive period rate',
    fr: 'Positive period rate',
  },
  {
    search: />\s*Average final value\s*</g,
    replace: `>{t('auto.average_final_value')}<`,
    key: 'auto.average_final_value',
    en: 'Average final value',
    fr: 'Average final value',
  },
  {
    search: />\s*Results by period\s*</g,
    replace: `>{t('auto.results_by_period')}<`,
    key: 'auto.results_by_period',
    en: 'Results by period',
    fr: 'Results by period',
  },
  {
    search: />\s*Month\s*</g,
    replace: `>{t('auto.month')}<`,
    key: 'auto.month',
    en: 'Month',
    fr: 'Month',
  },
  {
    search: />\s*async function handleSave\(event: FormEvent\s*</g,
    replace: `>{t('auto.async_function_handlesave_even')}<`,
    key: 'auto.async_function_handlesave_even',
    en: 'async function handleSave(event: FormEvent',
    fr: 'async function handleSave(event: FormEvent',
  },
  {
    search:
      />\s*Beginner tip: change only a few parameters at a time to compare strategies reliably\.\s*</g,
    replace: `>{t('auto.beginner_tip_change_only_a_few')}<`,
    key: 'auto.beginner_tip_change_only_a_few',
    en: 'Beginner tip: change only a few parameters at a time to compare strategies reliably.',
    fr: 'Beginner tip: change only a few parameters at a time to compare strategies reliably.',
  },
  {
    search: />\s*Strategy identity\s*</g,
    replace: `>{t('auto.strategy_identity')}<`,
    key: 'auto.strategy_identity',
    en: 'Strategy identity',
    fr: 'Strategy identity',
  },
  {
    search: />\s*Trading cycles \/ day\s*</g,
    replace: `>{t('auto.trading_cycles_day')}<`,
    key: 'auto.trading_cycles_day',
    en: 'Trading cycles / day',
    fr: 'Trading cycles / day',
  },
  {
    search: />\s*AI system prompt\s*</g,
    replace: `>{t('auto.ai_system_prompt')}<`,
    key: 'auto.ai_system_prompt',
    en: 'AI system prompt',
    fr: 'AI system prompt',
  },
  {
    search: />\s*AI context prompt\s*</g,
    replace: `>{t('auto.ai_context_prompt')}<`,
    key: 'auto.ai_context_prompt',
    en: 'AI context prompt',
    fr: 'AI context prompt',
  },
  {
    search: />\s*Define the weight of each crypto in the strategy\.\s*</g,
    replace: `>{t('auto.define_the_weight_of_each_cryp')}<`,
    key: 'auto.define_the_weight_of_each_cryp',
    en: 'Define the weight of each crypto in the strategy.',
    fr: 'Define the weight of each crypto in the strategy.',
  },
  {
    search: />\s*Prefill from profile\s*</g,
    replace: `>{t('auto.prefill_from_profile')}<`,
    key: 'auto.prefill_from_profile',
    en: 'Prefill from profile',
    fr: 'Prefill from profile',
  },
  {
    search: />\s*Advanced configuration\s*</g,
    replace: `>{t('auto.advanced_configuration')}<`,
    key: 'auto.advanced_configuration',
    en: 'Advanced configuration',
    fr: 'Advanced configuration',
  },
  {
    search: />\s*Fee preference\s*</g,
    replace: `>{t('auto.fee_preference')}<`,
    key: 'auto.fee_preference',
    en: 'Fee preference',
    fr: 'Fee preference',
  },
  {
    search: />\s*maker\s*</g,
    replace: `>{t('auto.maker')}<`,
    key: 'auto.maker',
    en: 'maker',
    fr: 'maker',
  },
  {
    search: />\s*taker\s*</g,
    replace: `>{t('auto.taker')}<`,
    key: 'auto.taker',
    en: 'taker',
    fr: 'taker',
  },
  {
    search: />\s*Decision mode\s*</g,
    replace: `>{t('auto.decision_mode')}<`,
    key: 'auto.decision_mode',
    en: 'Decision mode',
    fr: 'Decision mode',
  },
  {
    search: />\s*simple allocation\s*</g,
    replace: `>{t('auto.simple_allocation')}<`,
    key: 'auto.simple_allocation',
    en: 'simple allocation',
    fr: 'simple allocation',
  },
  {
    search: />\s*strategy rules\s*</g,
    replace: `>{t('auto.strategy_rules')}<`,
    key: 'auto.strategy_rules',
    en: 'strategy rules',
    fr: 'strategy rules',
  },
  {
    search: />\s*AI-assisted\s*</g,
    replace: `>{t('auto.ai_assisted')}<`,
    key: 'auto.ai_assisted',
    en: 'AI-assisted',
    fr: 'AI-assisted',
  },
  {
    search: />\s*Allow selling at a loss\s*</g,
    replace: `>{t('auto.allow_selling_at_a_loss')}<`,
    key: 'auto.allow_selling_at_a_loss',
    en: 'Allow selling at a loss',
    fr: 'Allow selling at a loss',
  },
  {
    search: />\s*Require a dip before buy\s*</g,
    replace: `>{t('auto.require_a_dip_before_buy')}<`,
    key: 'auto.require_a_dip_before_buy',
    en: 'Require a dip before buy',
    fr: 'Require a dip before buy',
  },
  {
    search: />\s*Recreate default strategies\s*</g,
    replace: `>{t('auto.recreate_default_strategies')}<`,
    key: 'auto.recreate_default_strategies',
    en: 'Recreate default strategies',
    fr: 'Recreate default strategies',
  },
  {
    search: />\s*Cancel editing\s*</g,
    replace: `>{t('auto.cancel_editing')}<`,
    key: 'auto.cancel_editing',
    en: 'Cancel editing',
    fr: 'Cancel editing',
  },
  {
    search:
      />\s*This page fully replaces YAML editing: every strategy is now configured through forms\.\s*</g,
    replace: `>{t('auto.this_page_fully_replaces_yaml')}<`,
    key: 'auto.this_page_fully_replaces_yaml',
    en: 'This page fully replaces YAML editing: every strategy is now configured through forms.',
    fr: 'This page fully replaces YAML editing: every strategy is now configured through forms.',
  },
  {
    search: />\s*Clean A\/B testing\s*</g,
    replace: `>{t('auto.clean_a_b_testing')}<`,
    key: 'auto.clean_a_b_testing',
    en: 'Clean A/B testing',
    fr: 'Clean A/B testing',
  },
  {
    search:
      />\s*Compare two strategies over the same period and with the same monthly budget\.\s*</g,
    replace: `>{t('auto.compare_two_strategies_over_th')}<`,
    key: 'auto.compare_two_strategies_over_th',
    en: 'Compare two strategies over the same period and with the same monthly budget.',
    fr: 'Compare two strategies over the same period and with the same monthly budget.',
  },
  {
    search: />\s*Beginner risk\s*</g,
    replace: `>{t('auto.beginner_risk')}<`,
    key: 'auto.beginner_risk',
    en: 'Beginner risk',
    fr: 'Beginner risk',
  },
  {
    search: />\s*If you are starting, begin with\s*</g,
    replace: `>{t('auto.if_you_are_starting_begin_with')}<`,
    key: 'auto.if_you_are_starting_begin_with',
    en: 'If you are starting, begin with',
    fr: 'If you are starting, begin with',
  },
  {
    search: />\s*and a low frequency \(1 or\s*</g,
    replace: `>{t('auto.and_a_low_frequency_1_or')}<`,
    key: 'auto.and_a_low_frequency_1_or',
    en: 'and a low frequency (1 or',
    fr: 'and a low frequency (1 or',
  },
  {
    search: />\s*2 cycles\/day\)\.\s*</g,
    replace: `>{t('auto.2_cycles_day')}<`,
    key: 'auto.2_cycles_day',
    en: '2 cycles/day).',
    fr: '2 cycles/day).',
  },
  {
    search: />\s*Concentration\s*</g,
    replace: `>{t('auto.concentration')}<`,
    key: 'auto.concentration',
    en: 'Concentration',
    fr: 'Concentration',
  },
  {
    search:
      />\s*Keep a reasonable max-per-asset limit to avoid over-depending on one crypto\.\s*</g,
    replace: `>{t('auto.keep_a_reasonable_max_per_asse')}<`,
    key: 'auto.keep_a_reasonable_max_per_asse',
    en: 'Keep a reasonable max-per-asset limit to avoid over-depending on one crypto.',
    fr: 'Keep a reasonable max-per-asset limit to avoid over-depending on one crypto.',
  },
  {
    search: />\s*Advanced, not complicated\s*</g,
    replace: `>{t('auto.advanced_not_complicated')}<`,
    key: 'auto.advanced_not_complicated',
    en: 'Advanced, not complicated',
    fr: 'Advanced, not complicated',
  },
  {
    search:
      />\s*Open advanced settings only when testing a precise hypothesis \(fees, slippage, cash\s*</g,
    replace: `>{t('auto.open_advanced_settings_only_wh')}<`,
    key: 'auto.open_advanced_settings_only_wh',
    en: 'Open advanced settings only when testing a precise hypothesis (fees, slippage, cash',
    fr: 'Open advanced settings only when testing a precise hypothesis (fees, slippage, cash',
  },
  {
    search: />\s*reserve, etc\.\)\.\s*</g,
    replace: `>{t('auto.reserve_etc')}<`,
    key: 'auto.reserve_etc',
    en: 'reserve, etc.).',
    fr: 'reserve, etc.).',
  },
  {
    search: />\s*Saved strategies\s*</g,
    replace: `>{t('auto.saved_strategies')}<`,
    key: 'auto.saved_strategies',
    en: 'Saved strategies',
    fr: 'Saved strategies',
  },
  {
    search: />\s*Budget\s*</g,
    replace: `>{t('auto.budget')}<`,
    key: 'auto.budget',
    en: 'Budget',
    fr: 'Budget',
  },
  {
    search: />\s*Cycles\s*</g,
    replace: `>{t('auto.cycles')}<`,
    key: 'auto.cycles',
    en: 'Cycles',
    fr: 'Cycles',
  },
  {
    search: />\s*Position max\s*</g,
    replace: `>{t('auto.position_max')}<`,
    key: 'auto.position_max',
    en: 'Position max',
    fr: 'Position max',
  },
  {
    search: />\s*Reserve\s*</g,
    replace: `>{t('auto.reserve')}<`,
    key: 'auto.reserve',
    en: 'Reserve',
    fr: 'Reserve',
  },
  {
    search: />\s*Slippage\s*</g,
    replace: `>{t('auto.slippage')}<`,
    key: 'auto.slippage',
    en: 'Slippage',
    fr: 'Slippage',
  },
  {
    search: />\s*Mode\s*</g,
    replace: `>{t('auto.mode')}<`,
    key: 'auto.mode',
    en: 'Mode',
    fr: 'Mode',
  },
  {
    search: />\s*Guardrails\s*</g,
    replace: `>{t('auto.guardrails')}<`,
    key: 'auto.guardrails',
    en: 'Guardrails',
    fr: 'Guardrails',
  },
  {
    search: />\s*Allocation\s*</g,
    replace: `>{t('auto.allocation')}<`,
    key: 'auto.allocation',
    en: 'Allocation',
    fr: 'Allocation',
  },
  {
    search: />\s*Duplicate\s*</g,
    replace: `>{t('auto.duplicate')}<`,
    key: 'auto.duplicate',
    en: 'Duplicate',
    fr: 'Duplicate',
  },
  {
    search: />\s*Select at least 2 strategies with the "Compare" button in the table above\.\s*</g,
    replace: `>{t('auto.select_at_least_2_strategies_w')}<`,
    key: 'auto.select_at_least_2_strategies_w',
    en: 'Select at least 2 strategies with the "Compare" button in the table above.',
    fr: 'Select at least 2 strategies with the "Compare" button in the table above.',
  },
  {
    search: />\s*Criterion\s*</g,
    replace: `>{t('auto.criterion')}<`,
    key: 'auto.criterion',
    en: 'Criterion',
    fr: 'Criterion',
  },
  {
    search: />\s*Monthly budget\s*</g,
    replace: `>{t('auto.monthly_budget')}<`,
    key: 'auto.monthly_budget',
    en: 'Monthly budget',
    fr: 'Monthly budget',
  },
  {
    search: />\s*Target allocation\s*</g,
    replace: `>{t('auto.target_allocation')}<`,
    key: 'auto.target_allocation',
    en: 'Target allocation',
    fr: 'Target allocation',
  },
  {
    search: />\s*Discover community-shared strategies and import them for local testing\.\s*</g,
    replace: `>{t('auto.discover_community_shared_stra')}<`,
    key: 'auto.discover_community_shared_stra',
    en: 'Discover community-shared strategies and import them for local testing.',
    fr: 'Discover community-shared strategies and import them for local testing.',
  },
  {
    search: />\s*No public strategy available at the moment\.\s*</g,
    replace: `>{t('auto.no_public_strategy_available_a')}<`,
    key: 'auto.no_public_strategy_available_a',
    en: 'No public strategy available at the moment.',
    fr: 'No public strategy available at the moment.',
  },
  {
    search: />\s*Share\s*</g,
    replace: `>{t('auto.share')}<`,
    key: 'auto.share',
    en: 'Share',
    fr: 'Share',
  },
  {
    search: />\s*Author\s*</g,
    replace: `>{t('auto.author')}<`,
    key: 'auto.author',
    en: 'Author',
    fr: 'Author',
  },
  {
    search: />\s*Import\s*</g,
    replace: `>{t('auto.import')}<`,
    key: 'auto.import',
    en: 'Import',
    fr: 'Import',
  },
  {
    search: />\s*Your Strategies\s*</g,
    replace: `>{t('auto.your_strategies')}<`,
    key: 'auto.your_strategies',
    en: 'Your Strategies',
    fr: 'Your Strategies',
  },
  {
    search: />\s*Export\s*</g,
    replace: `>{t('auto.export')}<`,
    key: 'auto.export',
    en: 'Export',
    fr: 'Export',
  },
  {
    search: />\s*Restore defaults\s*</g,
    replace: `>{t('auto.restore_defaults')}<`,
    key: 'auto.restore_defaults',
    en: 'Restore defaults',
    fr: 'Restore defaults',
  },
  {
    search: />\s*Create strategy\s*</g,
    replace: `>{t('auto.create_strategy')}<`,
    key: 'auto.create_strategy',
    en: 'Create strategy',
    fr: 'Create strategy',
  },
  {
    search: />\s*No strategy created yet\. Create your first strategy to get started\.\s*</g,
    replace: `>{t('auto.no_strategy_created_yet_create')}<`,
    key: 'auto.no_strategy_created_yet_create',
    en: 'No strategy created yet. Create your first strategy to get started.',
    fr: 'No strategy created yet. Create your first strategy to get started.',
  },
  {
    search: />\s*Create my first strategy\s*</g,
    replace: `>{t('auto.create_my_first_strategy')}<`,
    key: 'auto.create_my_first_strategy',
    en: 'Create my first strategy',
    fr: 'Create my first strategy',
  },
  {
    search: />\s*Type\s*</g,
    replace: `>{t('auto.type')}<`,
    key: 'auto.type',
    en: 'Type',
    fr: 'Type',
  },
  {
    search: />\s*Risk level\s*</g,
    replace: `>{t('auto.risk_level')}<`,
    key: 'auto.risk_level',
    en: 'Risk level',
    fr: 'Risk level',
  },
  {
    search: />\s*Created on\s*</g,
    replace: `>{t('auto.created_on')}<`,
    key: 'auto.created_on',
    en: 'Created on',
    fr: 'Created on',
  },
  {
    search: />\s*Strategy name \*\s*</g,
    replace: `>{t('auto.strategy_name')}<`,
    key: 'auto.strategy_name',
    en: 'Strategy name *',
    fr: 'Strategy name *',
  },
  {
    search: />\s*Cancel\s*</g,
    replace: `>{t('auto.cancel')}<`,
    key: 'auto.cancel',
    en: 'Cancel',
    fr: 'Cancel',
  },
  {
    search: />\s*Risk level \*\s*</g,
    replace: `>{t('auto.risk_level')}<`,
    key: 'auto.risk_level',
    en: 'Risk level *',
    fr: 'Risk level *',
  },
  {
    search: />\s*Defensive\s*</g,
    replace: `>{t('auto.defensive')}<`,
    key: 'auto.defensive',
    en: 'Defensive',
    fr: 'Defensive',
  },
  {
    search: />\s*Lower-volatility targeting with strict downside controls\.\s*</g,
    replace: `>{t('auto.lower_volatility_targeting_wit')}<`,
    key: 'auto.lower_volatility_targeting_wit',
    en: 'Lower-volatility targeting with strict downside controls.',
    fr: 'Lower-volatility targeting with strict downside controls.',
  },
  {
    search: />\s*Balanced\s*</g,
    replace: `>{t('auto.balanced')}<`,
    key: 'auto.balanced',
    en: 'Balanced',
    fr: 'Balanced',
  },
  {
    search: />\s*Medium risk with diversified execution\.\s*</g,
    replace: `>{t('auto.medium_risk_with_diversified_e')}<`,
    key: 'auto.medium_risk_with_diversified_e',
    en: 'Medium risk with diversified execution.',
    fr: 'Medium risk with diversified execution.',
  },
  {
    search: />\s*Aggressive\s*</g,
    replace: `>{t('auto.aggressive')}<`,
    key: 'auto.aggressive',
    en: 'Aggressive',
    fr: 'Aggressive',
  },
  {
    search: />\s*Strategy type \*\s*</g,
    replace: `>{t('auto.strategy_type')}<`,
    key: 'auto.strategy_type',
    en: 'Strategy type *',
    fr: 'Strategy type *',
  },
  {
    search: />\s*Fixed allocation and periodic rebalancing\.\s*</g,
    replace: `>{t('auto.fixed_allocation_and_periodic')}<`,
    key: 'auto.fixed_allocation_and_periodic',
    en: 'Fixed allocation and periodic rebalancing.',
    fr: 'Fixed allocation and periodic rebalancing.',
  },
  {
    search: />\s*Dynamic recommendations with guardrails and spending limits\.\s*</g,
    replace: `>{t('auto.dynamic_recommendations_with_g')}<`,
    key: 'auto.dynamic_recommendations_with_g',
    en: 'Dynamic recommendations with guardrails and spending limits.',
    fr: 'Dynamic recommendations with guardrails and spending limits.',
  },
  {
    search: />\s*Historical signals\s*</g,
    replace: `>{t('auto.historical_signals')}<`,
    key: 'auto.historical_signals',
    en: 'Historical signals',
    fr: 'Historical signals',
  },
  {
    search: />\s*Buy\/sell triggers based on historical price changes\.\s*</g,
    replace: `>{t('auto.buy_sell_triggers_based_on_his')}<`,
    key: 'auto.buy_sell_triggers_based_on_his',
    en: 'Buy/sell triggers based on historical price changes.',
    fr: 'Buy/sell triggers based on historical price changes.',
  },
  {
    search: />\s*Back\s*</g,
    replace: `>{t('auto.back')}<`,
    key: 'auto.back',
    en: 'Back',
    fr: 'Back',
  },
  {
    search: />\s*Portfolio allocation\s*</g,
    replace: `>{t('auto.portfolio_allocation')}<`,
    key: 'auto.portfolio_allocation',
    en: 'Portfolio allocation',
    fr: 'Portfolio allocation',
  },
  {
    search: />\s*Specify target percentage for each cryptocurrency:\s*</g,
    replace: `>{t('auto.specify_target_percentage_for')}<`,
    key: 'auto.specify_target_percentage_for',
    en: 'Specify target percentage for each cryptocurrency:',
    fr: 'Specify target percentage for each cryptocurrency:',
  },
  {
    search: />\s*Cryptocurrencies to monitor \*\s*</g,
    replace: `>{t('auto.cryptocurrencies_to_monitor')}<`,
    key: 'auto.cryptocurrencies_to_monitor',
    en: 'Cryptocurrencies to monitor *',
    fr: 'Cryptocurrencies to monitor *',
  },
  {
    search: />\s*Select at least 3 cryptos\s*</g,
    replace: `>{t('auto.select_at_least_3_cryptos')}<`,
    key: 'auto.select_at_least_3_cryptos',
    en: 'Select at least 3 cryptos',
    fr: 'Select at least 3 cryptos',
  },
  {
    search: />\s*Prompt template\s*</g,
    replace: `>{t('auto.prompt_template')}<`,
    key: 'auto.prompt_template',
    en: 'Prompt template',
    fr: 'Prompt template',
  },
  {
    search: />\s*⚠️ Suggestions:\s*</g,
    replace: `>{t('auto.suggestions')}<`,
    key: 'auto.suggestions',
    en: '⚠️ Suggestions:',
    fr: '⚠️ Suggestions:',
  },
  {
    search: />\s*Your custom prompt:\s*</g,
    replace: `>{t('auto.your_custom_prompt')}<`,
    key: 'auto.your_custom_prompt',
    en: 'Your custom prompt:',
    fr: 'Your custom prompt:',
  },
  {
    search: />\s*Select at least 2 cryptos\s*</g,
    replace: `>{t('auto.select_at_least_2_cryptos')}<`,
    key: 'auto.select_at_least_2_cryptos',
    en: 'Select at least 2 cryptos',
    fr: 'Select at least 2 cryptos',
  },
  {
    search: />\s*Minimum days between trades\s*</g,
    replace: `>{t('auto.minimum_days_between_trades')}<`,
    key: 'auto.minimum_days_between_trades',
    en: 'Minimum days between trades',
    fr: 'Minimum days between trades',
  },
  {
    search: />\s*Maximum concurrent positions\s*</g,
    replace: `>{t('auto.maximum_concurrent_positions')}<`,
    key: 'auto.maximum_concurrent_positions',
    en: 'Maximum concurrent positions',
    fr: 'Maximum concurrent positions',
  },
  {
    search: />\s*Enable rebalancing\s*</g,
    replace: `>{t('auto.enable_rebalancing')}<`,
    key: 'auto.enable_rebalancing',
    en: 'Enable rebalancing',
    fr: 'Enable rebalancing',
  },
  {
    search: />\s*AI usage guardrails\s*</g,
    replace: `>{t('auto.ai_usage_guardrails')}<`,
    key: 'auto.ai_usage_guardrails',
    en: 'AI usage guardrails',
    fr: 'AI usage guardrails',
  },
  {
    search: />\s*Maximum AI calls per month\s*</g,
    replace: `>{t('auto.maximum_ai_calls_per_month')}<`,
    key: 'auto.maximum_ai_calls_per_month',
    en: 'Maximum AI calls per month',
    fr: 'Maximum AI calls per month',
  },
  {
    search: />\s*Maximum concurrent AI positions\s*</g,
    replace: `>{t('auto.maximum_concurrent_ai_position')}<`,
    key: 'auto.maximum_concurrent_ai_position',
    en: 'Maximum concurrent AI positions',
    fr: 'Maximum concurrent AI positions',
  },
  {
    search: />\s*\/\/ Step 5: Review\s*</g,
    replace: `>{t('auto.step_5_review')}<`,
    key: 'auto.step_5_review',
    en: '// Step 5: Review',
    fr: '// Step 5: Review',
  },
  {
    search: />\s*Strategy summary\s*</g,
    replace: `>{t('auto.strategy_summary')}<`,
    key: 'auto.strategy_summary',
    en: 'Strategy summary',
    fr: 'Strategy summary',
  },
  {
    search: />\s*Name:\s*</g,
    replace: `>{t('auto.name')}<`,
    key: 'auto.name',
    en: 'Name:',
    fr: 'Name:',
  },
  {
    search: />\s*Description:\s*</g,
    replace: `>{t('auto.description')}<`,
    key: 'auto.description',
    en: 'Description:',
    fr: 'Description:',
  },
  {
    search: />\s*Type:\s*</g,
    replace: `>{t('auto.type')}<`,
    key: 'auto.type',
    en: 'Type:',
    fr: 'Type:',
  },
  {
    search: />\s*Risk level:\s*</g,
    replace: `>{t('auto.risk_level')}<`,
    key: 'auto.risk_level',
    en: 'Risk level:',
    fr: 'Risk level:',
  },
  {
    search: />\s*Monthly budget:\s*</g,
    replace: `>{t('auto.monthly_budget')}<`,
    key: 'auto.monthly_budget',
    en: 'Monthly budget:',
    fr: 'Monthly budget:',
  },
  {
    search: />\s*Daily maximum:\s*</g,
    replace: `>{t('auto.daily_maximum')}<`,
    key: 'auto.daily_maximum',
    en: 'Daily maximum:',
    fr: 'Daily maximum:',
  },
  {
    search: />\s*Decision checks\/day:\s*</g,
    replace: `>{t('auto.decision_checks_day')}<`,
    key: 'auto.decision_checks_day',
    en: 'Decision checks/day:',
    fr: 'Decision checks/day:',
  },
  {
    search: />\s*Minimum AI confidence:\s*</g,
    replace: `>{t('auto.minimum_ai_confidence')}<`,
    key: 'auto.minimum_ai_confidence',
    en: 'Minimum AI confidence:',
    fr: 'Minimum AI confidence:',
  },
  {
    search: />\s*Max position size:\s*</g,
    replace: `>{t('auto.max_position_size')}<`,
    key: 'auto.max_position_size',
    en: 'Max position size:',
    fr: 'Max position size:',
  },
  {
    search: />\s*Minimum order:\s*</g,
    replace: `>{t('auto.minimum_order')}<`,
    key: 'auto.minimum_order',
    en: 'Minimum order:',
    fr: 'Minimum order:',
  },
  {
    search: />\s*Sell at loss allowed:\s*</g,
    replace: `>{t('auto.sell_at_loss_allowed')}<`,
    key: 'auto.sell_at_loss_allowed',
    en: 'Sell at loss allowed:',
    fr: 'Sell at loss allowed:',
  },
  {
    search: />\s*Selected cryptos:\s*</g,
    replace: `>{t('auto.selected_cryptos')}<`,
    key: 'auto.selected_cryptos',
    en: 'Selected cryptos:',
    fr: 'Selected cryptos:',
  },
  {
    search: />\s*AI query frequency:\s*</g,
    replace: `>{t('auto.ai_query_frequency')}<`,
    key: 'auto.ai_query_frequency',
    en: 'AI query frequency:',
    fr: 'AI query frequency:',
  },
  {
    search: />\s*AI cost cap:\s*</g,
    replace: `>{t('auto.ai_cost_cap')}<`,
    key: 'auto.ai_cost_cap',
    en: 'AI cost cap:',
    fr: 'AI cost cap:',
  },
  {
    search: />\s*AI call limit:\s*</g,
    replace: `>{t('auto.ai_call_limit')}<`,
    key: 'auto.ai_call_limit',
    en: 'AI call limit:',
    fr: 'AI call limit:',
  },
  {
    search: />\s*AI session limit:\s*</g,
    replace: `>{t('auto.ai_session_limit')}<`,
    key: 'auto.ai_session_limit',
    en: 'AI session limit:',
    fr: 'AI session limit:',
  },
  {
    search: />\s*Analysis window:\s*</g,
    replace: `>{t('auto.analysis_window')}<`,
    key: 'auto.analysis_window',
    en: 'Analysis window:',
    fr: 'Analysis window:',
  },
  {
    search: />\s*Max capital \/ signal:\s*</g,
    replace: `>{t('auto.max_capital_signal')}<`,
    key: 'auto.max_capital_signal',
    en: 'Max capital / signal:',
    fr: 'Max capital / signal:',
  },
  {
    search: />\s*Trend lookback:\s*</g,
    replace: `>{t('auto.trend_lookback')}<`,
    key: 'auto.trend_lookback',
    en: 'Trend lookback:',
    fr: 'Trend lookback:',
  },
  {
    search: />\s*Max volatility:\s*</g,
    replace: `>{t('auto.max_volatility')}<`,
    key: 'auto.max_volatility',
    en: 'Max volatility:',
    fr: 'Max volatility:',
  },
  {
    search: />\s*Trade cooldown:\s*</g,
    replace: `>{t('auto.trade_cooldown')}<`,
    key: 'auto.trade_cooldown',
    en: 'Trade cooldown:',
    fr: 'Trade cooldown:',
  },
  {
    search: />\s*Monthly simulation preview\s*</g,
    replace: `>{t('auto.monthly_simulation_preview')}<`,
    key: 'auto.monthly_simulation_preview',
    en: 'Monthly simulation preview',
    fr: 'Monthly simulation preview',
  },
  {
    search: />\s*Estimated orders \/ month:\s*</g,
    replace: `>{t('auto.estimated_orders_month')}<`,
    key: 'auto.estimated_orders_month',
    en: 'Estimated orders / month:',
    fr: 'Estimated orders / month:',
  },
  {
    search: />\s*No blocking warning detected for this simulation\.\s*</g,
    replace: `>{t('auto.no_blocking_warning_detected_f')}<`,
    key: 'auto.no_blocking_warning_detected_f',
    en: 'No blocking warning detected for this simulation.',
    fr: 'No blocking warning detected for this simulation.',
  },
  {
    search: />\s*Preview simulation\s*</g,
    replace: `>{t('auto.preview_simulation')}<`,
    key: 'auto.preview_simulation',
    en: 'Preview simulation',
    fr: 'Preview simulation',
  },
  {
    search: />\s*Execution cadence\s*</g,
    replace: `>{t('auto.execution_cadence')}<`,
    key: 'auto.execution_cadence',
    en: 'Execution cadence',
    fr: 'Execution cadence',
  },
  {
    search: />\s*Decision checks per day\s*</g,
    replace: `>{t('auto.decision_checks_per_day')}<`,
    key: 'auto.decision_checks_per_day',
    en: 'Decision checks per day',
    fr: 'Decision checks per day',
  },
  {
    search: />\s*Promise\s*</g,
    replace: `>{t('auto.promise')}<`,
    key: 'auto.promise',
    en: 'Promise',
    fr: 'Promise',
  },
  {
    search: />\s*Record\s*</g,
    replace: `>{t('auto.record')}<`,
    key: 'auto.record',
    en: 'Record',
    fr: 'Record',
  },
  {
    search: />\s*\/\/ Wizard state\s*</g,
    replace: `>{t('auto.wizard_state')}<`,
    key: 'auto.wizard_state',
    en: '// Wizard state',
    fr: '// Wizard state',
  },
  {
    search: />\s*'balanced',\s*</g,
    replace: `>{t('auto.balanced')}<`,
    key: 'auto.balanced',
    en: "'balanced',",
    fr: "'balanced',",
  },
];
